# Generated by Django 2.1.2 on 2018-10-25 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='liked',
            fields=[
                ('usr', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='owned',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usr', models.IntegerField(default=0)),
                ('comment', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='raamatud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pealkiri', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=30)),
                ('kirjastus', models.CharField(max_length=30)),
                ('keel', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='owned',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booksearch.raamatud'),
        ),
        migrations.AddField(
            model_name='liked',
            name='book',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='booksearch.raamatud'),
        ),
    ]
