# Generated by Django 2.1.3 on 2018-11-19 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booksearch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookCovers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookID', models.IntegerField(null=True)),
                ('image', models.ImageField(null=True, upload_to='Images')),
            ],
        ),
        migrations.CreateModel(
            name='tracking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=30)),
                ('brauser', models.CharField(max_length=30)),
                ('os', models.CharField(max_length=30)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='wanted',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usr', models.IntegerField(default=0)),
                ('comment', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='liked',
            name='book',
        ),
        migrations.AddField(
            model_name='raamatud',
            name='ilmumisaasta',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='raamatud',
            name='lehekülgi',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='liked',
        ),
        migrations.AddField(
            model_name='wanted',
            name='book',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='booksearch.raamatud'),
        ),
    ]
